#!/bin/bash

cd /netshare1/home1/szzhongxin/proj1/hansun/snpIndel3/snp/snp3030

java -Xmx32g -jar /netshare1/home1/people/hansun/GATK/GenomeAnalysisTK.jar \
   -T ApplyRecalibration \
   -R /netshare1/home1/people/hansun/GATK/bundle/ucsc.hg19.fasta \
   -input  raw.snp.vcf \
   --ts_filter_level 99.0 \
   -tranchesFile raw.snp.tranche \
   -recalFile raw.snp.recal \
   -o raw.snp.recalibrated.vcf \
   -mode SNP

#cd /netshare1/home1/szzhongxin/proj1/hansun/snpIndel/snp/snp5050
#
#java -Xmx7g -jar /netshare1/home1/people/hansun/GATK/GenomeAnalysisTK.jar \
#   -T ApplyRecalibration \
#   -R /netshare1/home1/people/hansun/GATK/bundle/ucsc.hg19.fasta \
#   -input  raw.snp.vcf \
#   --ts_filter_level 99.0 \
#   -tranchesFile raw.snp.tranche \
#   -recalFile raw.snp.recal \
#   -o raw.snp.recalibrated.vcf \
#   -mode SNP
