perl pep2dna_1.pl splicing_point_1_2
perl pep2dna_2.pl splicing_point_1_2_complete
perl pep2dna_3.pl splicing_point_1_2_complete_c
perl pep2dna_4.pl splicing_point_1_2_complete_c_title
perl pep2dna_5.pl splicing_point_1_2_complete_c_title splicing_point_1_3
perl pep2dna_6.pl splicing_point_1_2_complete_c_title_dna
