#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/snpIndel/indel/indelN


java -Xmx4g -jar /netshare1/home1/people/hansun/GATK/GenomeAnalysisTK.jar \
-R /netshare1/home1/people/hansun/GATK/bundle/ucsc.hg19.fasta \
-T UnifiedGenotyper \
-glm INDEL \
-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping/3A/3A.realigned.recalibrated.bam \
--dbsnp /netshare1/home1/people/hansun/GATK/bundle/dbsnp_132.hg19.vcf \
-o raw.indel3a.vcf \
-metrics raw.indel3a.metrics \
-stand_call_conf 30 \
-stand_emit_conf 30
