cd /fs01/szzhongxin/proj1/hansun/12sViruses/4-paired
#python CHC1A.seq.py
#python CHC2A.seq.py
#python CHC3A.seq.py
#python CHC4A.seq.py
#python CHC8A.seq.py
#python CHC9A.seq.py
#python ICC1A.seq.py
python ICC2A.seq.py
python ICC3A.seq.py
python ICC6A.seq.py
python ICC7A.seq.py
python ICC8A.seq.py
