#qsub varScan.chc6.chr10.sh -l nodes=n4 -q high 
#qsub varScan.chc6.chr11.sh -l nodes=n5 -q high 
#qsub varScan.chc6.chr12.sh -l nodes=n6 -q high 
#qsub varScan.chc6.chr13.sh -l nodes=n7 -q high 
#qsub varScan.chc6.chr14.sh -l nodes=n9 -q high 
#qsub varScan.chc6.chr15.sh -l nodes=n10 -q high 
#qsub varScan.chc6.chr16.sh -l nodes=n11 -q high 
#qsub varScan.chc6.chr17.sh -l nodes=n12 -q high 
#qsub varScan.chc6.chr18.sh -l nodes=n13 -q high 
#qsub varScan.chc6.chr19.sh -l nodes=n14 -q high 
#qsub varScan.chc6.chr1.sh -l nodes=n15 -q high 
#qsub varScan.chc6.chr20.sh -l nodes=n16 -q high 
#qsub varScan.chc6.chr21.sh -l nodes=n17 -q high 
#qsub varScan.chc6.chr22.sh -l nodes=n19 -q high 
#qsub varScan.chc6.chr2.sh -l nodes=n21 -q high 
#qsub varScan.chc6.chr3.sh -l nodes=n22 -q high 
qsub varScan.chc6.chr4.sh -l nodes=cu01  
qsub varScan.chc6.chr5.sh -l nodes=cu02  
qsub varScan.chc6.chr6.sh -l nodes=cu03 
qsub varScan.chc6.chr7.sh -l nodes=cu04 
qsub varScan.chc6.chr8.sh -l nodes=cu05 
qsub varScan.chc6.chr9.sh -l nodes=cu06 
qsub varScan.chc6.chrX.sh -l nodes=cu07 
qsub varScan.chc6.chrY.sh -l nodes=cu08 
