#!/bin/bash

cd /netshare1/home1/szzhongxin/proj1/hansun/aftmapping/9A



java -Xmx4g -jar \
/netshare1/home1/people/hansun/GATK/GenomeAnalysisTK.jar \
   -R /netshare1/home1/people/hansun/GATK/bundle/ucsc.hg19.fasta \
   -knownSites /netshare1/home1/people/hansun/GATK/bundle/dbsnp_132.hg19.vcf \
   -I 9A.realigned.bam \
   -T CountCovariates \
   -cov ReadGroupCovariate \
   -cov QualityScoreCovariate \
   -cov CycleCovariate \
   -cov DinucCovariate \
   -recalFile 9A.realigned.covariate.csv
