#!/bin/bash

sam=10B.CTTGTA_L002_w4q20m35_N.sam
bam=10B.CTTGTA_L002_w4q20m35_N.bam
bamsorted=10B.CTTGTA_L002_w4q20m35_N.sorted
bamsortedbam=10B.CTTGTA_L002_w4q20m35_N.sorted.bam
stat=10B.stat
BAM=10B.bam

cd /netshare1/home1/szzhongxin/proj1/hansun/mapping3/10B
samtools view -bS -o $bam $sam
rm $sam
samtools  sort $bam $bamsorted
samtools  flagstat $bamsortedbam >$stat
mv $bamsortedbam $BAM
samtools index $BAM
