#!/bin/bash

sam=4B.TAGCTT_L004_w4q20m35_N.sam
bam=4B.TAGCTT_L004_w4q20m35_N.bam
bamsorted=4B.TAGCTT_L004_w4q20m35_N.sorted
bamsortedbam=4B.TAGCTT_L004_w4q20m35_N.sorted.bam
stat=4B.stat
BAM=4B.bam

cd /netshare1/home1/szzhongxin/proj1/hansun/mapping3/4B
samtools view -bS -o $bam $sam
rm $sam
samtools  sort $bam $bamsorted
samtools  flagstat $bamsortedbam >$stat
mv $bamsortedbam $BAM
samtools index $BAM
