#!/bin/bash

sam=9B.GGCTAC_L001_w4q20m35_N.sam
bam=9B.GGCTAC_L001_w4q20m35_N.bam
bamsorted=9B.GGCTAC_L001_w4q20m35_N.sorted
bamsortedbam=9B.GGCTAC_L001_w4q20m35_N.sorted.bam
stat=9B.stat
BAM=9B.bam

cd /netshare1/home1/szzhongxin/proj1/hansun/mapping3/9B
samtools view -bS -o $bam $sam
rm $sam
samtools  sort $bam $bamsorted
samtools  flagstat $bamsortedbam >$stat
mv $bamsortedbam $BAM
samtools index $BAM
