#data=read.table("snpindel_snp3030_raw.snp.recalibrated.annovar.exonic_variant_function_new_nonsynonymous_SNV.heatmap")
#data=as.matrix(data)
#colnames(data)=c("1A","2A","3A","4A","5A","6A","7A","8A")
#pdf("snpindel_snp3030_raw.snp.recalibrated.annovar.exonic_variant_function_new_nonsynonymous_SNV.heatmap.pdf")
#hv<-heatmap(data,col=topo.colors(100),scale="none",keep.dendro=T,labRow="")
#dev.off()
#
#data=read.table("snpindel_snp3030_raw.snp.recalibrated.annovar.exonic_variant_function_dbsnp_nonsynonymous_SNV.heatmap")
#data=as.matrix(data)
#colnames(data)=c("1A","2A","3A","4A","5A","6A","7A","8A")
#pdf("snpindel_snp3030_raw.snp.recalibrated.annovar.exonic_variant_function_dbsnp_nonsynonymous_SNV.heatmap.pdf")
#hv<-heatmap(data,col=topo.colors(100),scale="none",keep.dendro=T,labRow="")
#dev.off()


data=read.table("snpindel2_snp3030_raw.snp.recalibrated.annovar.exonic_variant_function_new_nonsynonymous_SNV.heatmap")
data=as.matrix(data)
colnames(data)=c("1A","2A","3A","4A","5A","6A","7A","8A")
pdf("snpindel2_snp3030_raw.snp.recalibrated.annovar.exonic_variant_function_new_nonsynonymous_SNV.heatmap.pdf")
hv<-heatmap(data,col=topo.colors(100),scale="none",labRow="")
dev.off()

#data=read.table("snpindel2_snp3030_raw.snp.recalibrated.annovar.exonic_variant_function_dbsnp_nonsynonymous_SNV.heatmap")
#data=as.matrix(data)
#colnames(data)=c("1A","2A","3A","4A","5A","6A","7A","8A")
#pdf("snpindel2_snp3030_raw.snp.recalibrated.annovar.exonic_variant_function_dbsnp_nonsynonymous_SNV.heatmap.pdf")
#hv<-heatmap(data,col=topo.colors(100),scale="none",keep.dendro=T,labRow="")
#dev.off()
