#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/snpIndel/snp/snpN


java -Xmx4g -jar /netshare1/home1/people/hansun/GATK/GenomeAnalysisTK.jar \
-R /netshare1/home1/people/hansun/GATK/bundle/ucsc.hg19.fasta \
-T UnifiedGenotyper \
-glm SNP \
--dbsnp /netshare1/home1/people/hansun/GATK/bundle/dbsnp_132.hg19.vcf \
-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping/4A/4A.realigned.recalibrated.bam \
-o raw.snp4a.vcf \
-metrics raw.snp4a.metrics \
-stand_call_conf 30 \
-stand_emit_conf 30
