#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/snpIndel2/snp/snp3030


java -Xmx4g -jar /netshare1/home1/people/hansun/GATK/GenomeAnalysisTK.jar \
-R /netshare1/home1/people/hansun/GATK/bundle/ucsc.hg19.fasta \
-T UnifiedGenotyper \
-glm SNP \
-nt 8 \
--dbsnp /netshare1/home1/people/hansun/GATK/bundle/dbsnp_132.hg19.vcf \
-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/1A/1A.realigned.recalibrated.bam \
-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/2A/2A.realigned.recalibrated.bam \
-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/3A/3A.realigned.recalibrated.bam \
-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/4A/4A.realigned.recalibrated.bam \
-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/5A/5A.realigned.recalibrated.bam \
-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/6A/6A.realigned.recalibrated.bam \
-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/7A/7A.realigned.recalibrated.bam \
-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/8A/8A.realigned.recalibrated.bam \
-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/9A/9A.realigned.recalibrated.bam \
-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/10A/10A.realigned.recalibrated.bam \
-o raw.snp.vcf \
-metrics raw.snp.metrics \
-stand_call_conf 30 \
-stand_emit_conf 30

#cd  /netshare1/home1/szzhongxin/proj1/hansun/snpIndel2/snp/snp5050
#
#
#java -Xmx4g -jar /netshare1/home1/people/hansun/GATK/GenomeAnalysisTK.jar \
#-R /netshare1/home1/people/hansun/GATK/bundle/ucsc.hg19.fasta \
#-T UnifiedGenotyper \
#-glm SNP \
#-nt 8 \
#--dbsnp /netshare1/home1/people/hansun/GATK/bundle/dbsnp_132.hg19.vcf \
#-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/1A/1A.realigned.recalibrated.bam \
#-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/2A/2A.realigned.recalibrated.bam \
#-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/3A/3A.realigned.recalibrated.bam \
#-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/4A/4A.realigned.recalibrated.bam \
#-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/5A/5A.realigned.recalibrated.bam \
#-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/6A/6A.realigned.recalibrated.bam \
#-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/7A/7A.realigned.recalibrated.bam \
#-I /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2/8A/8A.realigned.recalibrated.bam \
#-o raw.snp.vcf \
#-metrics raw.snp.metrics \
#-stand_call_conf 50 \
#-stand_emit_conf 50
