cd /netshare1/home1/szzhongxin/proj1/hansun/SV/Mosaik

export MOSAIK_TMP=/netshare1/home1/szzhongxin/proj1/hansun/SV/Mosaik

#MosaikJump -ia ucsc.hg19.dat -out ucsc.hg19_15 -hs 15 -mem 6

#MosaikBuild -fr ucsc.hg19.fasta -oa  ucsc.hg19.dat

#MosaikBuild -q /netshare1/home1/szzhongxin/proj1/fudan2/1A/hiseq_20110926_lane5_w4q20m35_N.1.fq -q2 /netshare1/home1/szzhongxin/proj1/fudan2/1A/hiseq_20110926_lane5_w4q20m35_N.2.fq -out hiseq_20110926_lane5_w4q20m35_N.dat -st illumina -mfl 100


MosaikAligner -in hiseq_20110926_lane5_w4q20m35_N.dat -out hiseq_20110926_lane5_w4q20m35_N.aligned.dat -ia ucsc.hg19.dat -hs 15 -mm 4 -mhp 100 -act 20 -j ucsc.hg19_15  -annpe /netshare1/home1/people/hansun/MySoft/Mosaik/MOSAIK-2.1.33-source/networkFile/2.1.26.pe.100.0065.ann -annse /netshare1/home1/people/hansun/MySoft/Mosaik/MOSAIK-2.1.33-source/networkFile/2.1.26.se.100.005.ann  -lm


#MosaikAssembler -ia ucsc.hg19.dat -in hiseq_20110926_lane5_w4q20m35_N.aligned.sorted.dat  -out hiseq_20110926_lane5_w4q20m35_N.aligned.sorted.assembled


