#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/mapping5/10A

#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan5/10A/read_q20w5m35.1.fq \
#>10A.1.sai
#
#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan5/10A/read_q20w5m35.2.fq \
#>10A.2.sai
#
#
#bwa sampe  \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#10A.1.sai \
#10A.2.sai \
#/netshare1/home1/szzhongxin/proj1/fudan5/10A/read_q20w5m35.1.fq \
#/netshare1/home1/szzhongxin/proj1/fudan5/10A/read_q20w5m35.2.fq \
#-r "@RG\tID:10a\tSM:10a\tLB:10a\tPL:illumina\tPU:barcode" | \
#samtools view -bS -o 10A.bam -
#
#samtools  sort 10A.bam 10A.sorted
#mv 10A.sorted.bam 10A.bam
#samtools index 10A.bam
#samtools  flagstat 10A.bam >10A.stat

samtools rmdup -S 10A.bam 10A.rmduped.bam
mv 10A.rmduped.bam 10A.bam
samtools index 10A.bam
samtools  flagstat 10A.bam >10A.stat2

