#!/bin/bash

cd /netshare1/home1/szzhongxin/proj1/hansun/mapping5/4A

bwa aln -I -t 6 \
/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
/netshare1/home1/szzhongxin/proj1/fudan/4A/hiseq_20110824_lane8_w4q20m35_N.1.fq \
>4A.hiseq_20110824_lane8_w4q20m35_N.1.sai
#
bwa aln -I -t 6 \
/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
/netshare1/home1/szzhongxin/proj1/fudan/4A/hiseq_20110824_lane8_w4q20m35_N.2.fq \
>4A.hiseq_20110824_lane8_w4q20m35_N.2.sai

bwa sampe  \
-r "@RG\tID:4a\tSM:4a\tLB:4a\tPL:illumina\tPU:barcode" \
/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
4A.hiseq_20110824_lane8_w4q20m35_N.1.sai \
4A.hiseq_20110824_lane8_w4q20m35_N.2.sai \
/netshare1/home1/szzhongxin/proj1/fudan/4A/hiseq_20110824_lane8_w4q20m35_N.1.fq \
/netshare1/home1/szzhongxin/proj1/fudan/4A/hiseq_20110824_lane8_w4q20m35_N.2.fq | \
samtools view -bS -o 4A.hiseq_20110824_lane8_w4q20m35_N.bam -

samtools sort 4A.hiseq_20110824_lane8_w4q20m35_N.bam 4A.hiseq_20110824_lane8_w4q20m35_N.sorted
