#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/mapping5/9A

#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan5/9A/read_q20w5m35.1.fq \
#>9A.1.sai
#
#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan5/9A/read_q20w5m35.2.fq \
#>9A.2.sai
#
#
#bwa sampe  \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#9A.1.sai \
#9A.2.sai \
#/netshare1/home1/szzhongxin/proj1/fudan5/9A/read_q20w5m35.1.fq \
#/netshare1/home1/szzhongxin/proj1/fudan5/9A/read_q20w5m35.2.fq \
#-r "@RG\tID:9a\tSM:9a\tLB:9a\tPL:illumina\tPU:barcode" | \
#samtools view -bS -o 9A.bam -
#
#samtools  sort 9A.bam 9A.sorted
#mv 9A.sorted.bam 9A.bam
#samtools index 9A.bam
#samtools  flagstat 9A.bam >9A.stat

samtools rmdup -S 9A.bam 9A.rmduped.bam
mv 9A.rmduped.bam 9A.bam
samtools index 9A.bam
samtools  flagstat 9A.bam >9A.stat2
