#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/mapping6/5A

#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan6/5A/read_q20w5m35.1.fq \
#>5A.1.sai
#
#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan6/5A/read_q20w5m35.2.fq \
#>5A.2.sai
#
#
#bwa sampe  \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#5A.1.sai \
#5A.2.sai \
#/netshare1/home1/szzhongxin/proj1/fudan6/5A/read_q20w5m35.1.fq \
#/netshare1/home1/szzhongxin/proj1/fudan6/5A/read_q20w5m35.2.fq \
#-r "@RG\tID:m5a\tSM:m5a\tLB:m5a\tPL:illumina\tPU:barcode" | \
#samtools view -bS -o 5A.bam -
#
#samtools  sort 5A.bam 5A.sorted
#mv 5A.sorted.bam 5A.bam
#samtools index 5A.bam
#samtools  flagstat 5A.bam >5A.stat

samtools rmdup -S 5A.bam 5A.rmduped.bam
mv 5A.rmduped.bam 5A.bam
samtools index 5A.bam
samtools  flagstat 5A.bam >5A.stat2
