#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/Viruses/mapping/6A

bwa aln -I -t 6 \
/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
/netshare1/home1/szzhongxin/proj1/fudan/6A/hiseq20110714_lane6_read12_w4q10m35_N.1.fq \
>6A.hiseq20110714_lane6_read12_w4q10m35_N.1.sai
#
bwa aln -I -t 6 \
/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
/netshare1/home1/szzhongxin/proj1/fudan/6A/hiseq20110714_lane6_read12_w4q10m35_N.2.fq \
>6A.hiseq20110714_lane6_read12_w4q10m35_N.2.sai


bwa sampe  \
/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
6A.hiseq20110714_lane6_read12_w4q10m35_N.1.sai \
6A.hiseq20110714_lane6_read12_w4q10m35_N.2.sai \
/netshare1/home1/szzhongxin/proj1/fudan/6A/hiseq20110714_lane6_read12_w4q10m35_N.1.fq \
/netshare1/home1/szzhongxin/proj1/fudan/6A/hiseq20110714_lane6_read12_w4q10m35_N.2.fq \
-r "@RG\tID:6a\tSM:6a\tLB:6a\tPL:illumina\tPU:barcode" | \
samtools view -bS -o 6A.hiseq20110714_lane6_read12_w4q10m35_N.bam -

samtools  sort 6A.hiseq20110714_lane6_read12_w4q10m35_N.bam 6A.hiseq20110714_lane6_read12_w4q10m35_N.sorted

