cd /netshare1/home1/people/hansun/StopGainProteomics/5.tandem
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-21.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-22.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-23.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-2-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-21.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-22.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-23.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-24.xml
