cd /netshare1/home1/people/hansun/StopGainProteomics/5.tandem
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-21.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-3-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-4-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-07.xml
