cd /netshare1/home1/people/hansun/StopGainProteomics/5.tandem
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-21.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-22.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-21.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-22.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-23.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-24.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-1-25.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-18.xml
