cd /netshare1/home1/people/hansun/StopGainProteomics/5.tandem
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-8-21.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A1-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_LM6-A2-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-6_SNU398-1-17.xml
