cd /netshare1/home1/people/hansun/StopGainProteomics/5.tandem
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-5-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-6-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_Hep3B-7-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-1-07.xml
