cd /netshare1/home1/people/hansun/StopGainProteomics/5.tandem
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-7-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM3-8-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-14.xml
