cd /netshare1/home1/people/hansun/StopGainProteomics/5.tandem
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-3-25.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-21.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-22.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-23.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-24.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-4-25.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-5-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-4_LM3-6-14.xml
