cd /netshare1/home1/people/hansun/StopGainProteomics/5.tandem
tandem.exe inputxml/input_Cell-Line-mzxml-2_97L-A1-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-2_97L-A1-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-2_97L-A1-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-2_97L-A1-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-2_97L-A1-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-2_97L-A1-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-2_97L-A1-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-2_97L-A1-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-2_97L-A1-21.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_97L-A2-21.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-21.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-1-22.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-3_Hep3B-2-08.xml
