cd /netshare1/home1/people/hansun/StopGainProteomics/5.tandem
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-22.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-23.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-24.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-25.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-3-26.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-21.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-22.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-23.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-4-24.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-05.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-06.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-07.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-08.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-09.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-10.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-11.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-12.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-13.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-14.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-15.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-16.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-17.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-18.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-19.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-5-20.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-01.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-02.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-03.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-04.xml
tandem.exe inputxml/input_Cell-Line-mzxml-5_LM6-6-05.xml
