#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/Viruses/mapping/1A

bwa aln -I -t 6 \
/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
/netshare1/home1/szzhongxin/proj1/fudan/1A/hiseq_20110602_lane5_w4q20m35_N.1.fq \
>1A.hiseq_20110602_lane5_w4q20m35_N.1.sai

bwa aln -I -t 6 \
/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
/netshare1/home1/szzhongxin/proj1/fudan/1A/hiseq_20110602_lane5_w4q20m35_N.2.fq \
>1A.hiseq_20110602_lane5_w4q20m35_N.2.sai


bwa sampe  \
/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
1A.hiseq_20110602_lane5_w4q20m35_N.1.sai \
1A.hiseq_20110602_lane5_w4q20m35_N.2.sai \
/netshare1/home1/szzhongxin/proj1/fudan/1A/hiseq_20110602_lane5_w4q20m35_N.1.fq \
/netshare1/home1/szzhongxin/proj1/fudan/1A/hiseq_20110602_lane5_w4q20m35_N.2.fq \
-r "@RG\tID:1a\tSM:1a\tLB:1a\tPL:illumina\tPU:barcode" | \
samtools view -bS -o 1A.hiseq_20110602_lane5_w4q20m35_N.bam -

samtools  sort 1A.hiseq_20110602_lane5_w4q20m35_N.bam 1A.hiseq_20110602_lane5_w4q20m35_N.sorted


