#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/Viruses/mapping/7A

bwa aln -I -t 6 \
/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
/netshare1/home1/szzhongxin/proj1/fudan/7A/hiseq20110714_lane7_read12_w4q10m35_N.1.fq \
>7A.hiseq20110714_lane7_read12_w4q10m35_N.1.sai
#
bwa aln -I -t 6 \
/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
/netshare1/home1/szzhongxin/proj1/fudan/7A/hiseq20110714_lane7_read12_w4q10m35_N.2.fq \
>7A.hiseq20110714_lane7_read12_w4q10m35_N.2.sai


bwa sampe  \
/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
7A.hiseq20110714_lane7_read12_w4q10m35_N.1.sai \
7A.hiseq20110714_lane7_read12_w4q10m35_N.2.sai \
/netshare1/home1/szzhongxin/proj1/fudan/7A/hiseq20110714_lane7_read12_w4q10m35_N.1.fq \
/netshare1/home1/szzhongxin/proj1/fudan/7A/hiseq20110714_lane7_read12_w4q10m35_N.2.fq \
-r "@RG\tID:7a\tSM:7a\tLB:7a\tPL:illumina\tPU:barcode" | \
samtools view -bS -o 7A.hiseq20110714_lane7_read12_w4q10m35_N.bam -

samtools  sort  7A.hiseq20110714_lane7_read12_w4q10m35_N.bam  7A.hiseq20110714_lane7_read12_w4q10m35_N.sorted

