#qsub samtools.chr1.sh -l nodes=n4 -q high 
#qsub samtools.chr2.sh -l nodes=n5 -q high 
#qsub samtools.chr3.sh -l nodes=n6 -q high 
#qsub samtools.chr4.sh -l nodes=n7 -q high 
#qsub samtools.chr5.sh -l nodes=n9 -q high 
#qsub samtools.chr6.sh -l nodes=n10 -q high 
#qsub samtools.chr7.sh -l nodes=n11 -q high 
#qsub samtools.chr8.sh -l nodes=n12 -q high 
#qsub samtools.chr9.sh -l nodes=n13 -q high 
#qsub samtools.chr10.sh -l nodes=n14 -q high 
#qsub samtools.chr11.sh -l nodes=n15 -q high 
#qsub samtools.chr12.sh -l nodes=n16 -q high 
#qsub samtools.chr13.sh -l nodes=n17 -q high 
#qsub samtools.chr14.sh -l nodes=n19 -q high 
#qsub samtools.chr15.sh -l nodes=n21 -q high 
#qsub samtools.chr16.sh -l nodes=n22 -q high 
#qsub samtools.chr17.sh -l nodes=n23 -q high 
#qsub samtools.chr18.sh -l nodes=n24 -q high 
#qsub samtools.chr19.sh -l nodes=n25 -q high 
#qsub samtools.chr20.sh -l nodes=n26 -q high 
qsub samtools.chr21.sh -l nodes=cu14  
qsub samtools.chr22.sh -l nodes=cu15 
qsub samtools.chrX.sh -l nodes=cu16 
qsub samtools.chrY.sh -l nodes=cu17 
