qsub qsubtandem/input_jw_1014M.sh
qsub qsubtandem/input_jw_1516M.sh
qsub qsubtandem/input_jw_15N.sh
qsub qsubtandem/input_jw_15Nr.sh
qsub qsubtandem/input_jw_16c.sh
qsub qsubtandem/input_jw_16N.sh
qsub qsubtandem/input_jw_17c.sh
qsub qsubtandem/input_jw_17cr.sh
qsub qsubtandem/input_jw_17M.sh
qsub qsubtandem/input_jw_17Mr.sh
qsub qsubtandem/input_jw_17N.sh
qsub qsubtandem/input_jw_18c.sh
qsub qsubtandem/input_jw_18cr.sh
qsub qsubtandem/input_jw_18M.sh
qsub qsubtandem/input_jw_18N.sh
qsub qsubtandem/input_jw_19cr.sh
qsub qsubtandem/input_jw_19M.sh
qsub qsubtandem/input_jw_1_9N.sh
qsub qsubtandem/input_jw_19N.sh
qsub qsubtandem/input_jw_20c.sh
qsub qsubtandem/input_jw_20M.sh
qsub qsubtandem/input_jw_20N.sh
qsub qsubtandem/input_JW21_22M1.sh
qsub qsubtandem/input_JW21_22M2.sh
qsub qsubtandem/input_jw_21c.sh
qsub qsubtandem/input_jw_21cr.sh
qsub qsubtandem/input_jw_21M.sh
qsub qsubtandem/input_jw_21N.sh
qsub qsubtandem/input_jw_21Nr.sh
qsub qsubtandem/input_jw_22c.sh
qsub qsubtandem/input_jw_22M.sh
qsub qsubtandem/input_jw_22N.sh
qsub qsubtandem/input_jw_22Nr.sh
qsub qsubtandem/input_jw_23cr.sh
qsub qsubtandem/input_jw_23crr.sh
qsub qsubtandem/input_jw_23M.sh
qsub qsubtandem/input_jw_23N.sh
qsub qsubtandem/input_jw_24c.sh
qsub qsubtandem/input_jw_24cr.sh
qsub qsubtandem/input_jw_24M.sh
qsub qsubtandem/input_jw_24N.sh
qsub qsubtandem/input_jw_25c.sh
qsub qsubtandem/input_jw_25cr.sh
qsub qsubtandem/input_jw_25M.sh
qsub qsubtandem/input_jw_25N.sh
qsub qsubtandem/input_jw_26c.sh
qsub qsubtandem/input_jw_26M.sh
qsub qsubtandem/input_jw_26N.sh
qsub qsubtandem/input_jw_27c.sh
qsub qsubtandem/input_jw_27M.sh
qsub qsubtandem/input_jw_27N.sh
qsub qsubtandem/input_jw_28c.sh
qsub qsubtandem/input_jw_28cr.sh
qsub qsubtandem/input_jw_28M.sh
qsub qsubtandem/input_jw_28N.sh
qsub qsubtandem/input_jw_2930c.sh
qsub qsubtandem/input_jw_2930cr.sh
qsub qsubtandem/input_jw_2930N.sh
qsub qsubtandem/input_jw_29M.sh
qsub qsubtandem/input_jw_3031M.sh
qsub qsubtandem/input_jw_3132c.sh
qsub qsubtandem/input_jw_3132N.sh
qsub qsubtandem/input_jw_3233M.sh
qsub qsubtandem/input_jw_3334c.sh
qsub qsubtandem/input_jw_3334N.sh
qsub qsubtandem/input_jw_3334Nr.sh
qsub qsubtandem/input_jw_3435M.sh
qsub qsubtandem/input_jw_3536c.sh
qsub qsubtandem/input_jw_3536cr.sh
qsub qsubtandem/input_jw_3537N.sh
qsub qsubtandem/input_jw_3637M.sh
qsub qsubtandem/input_jw_3738c.sh
qsub qsubtandem/input_jw_3738cr.sh
qsub qsubtandem/input_jw_3839M.sh
qsub qsubtandem/input_jw_3840N.sh
qsub qsubtandem/input_jw_3940c.sh
qsub qsubtandem/input_jw_3940cr.sh
qsub qsubtandem/input_jw_4041M.sh
qsub qsubtandem/input_jw_4142c.sh
qsub qsubtandem/input_jw_4142cr.sh
qsub qsubtandem/input_jw_4143N.sh
qsub qsubtandem/input_jw_4243M.sh
qsub qsubtandem/input_jw_4344cr.sh
qsub qsubtandem/input_jw_4445M.sh
qsub qsubtandem/input_jw_4446N.sh
qsub qsubtandem/input_jw_4552c.sh
qsub qsubtandem/input_jw_4750N.sh
qsub qsubtandem/input_jw_5154N.sh
qsub qsubtandem/input_jw_5558N.sh
