#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/mapping/1A

#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan/1A/hiseq20110714_lane4_read12_w4q10m35_N.1.fq \
#>1A.hiseq20110714_lane4_read12_w4q10m35_N.1.sai

#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan/1A/hiseq20110714_lane4_read12_w4q10m35_N.2.fq \
#>1A.hiseq20110714_lane4_read12_w4q10m35_N.2.sai


bwa sampe \
/netshare1/home1/people/hansun/GATK/bwa/hg19 \
1A.hiseq20110714_lane4_read12_w4q10m35_N.1.sai \
1A.hiseq20110714_lane4_read12_w4q10m35_N.2.sai \
/netshare1/home1/szzhongxin/proj1/fudan/1A/hiseq20110714_lane4_read12_w4q10m35_N.1.fq \
/netshare1/home1/szzhongxin/proj1/fudan/1A/hiseq20110714_lane4_read12_w4q10m35_N.2.fq \
-r "@RG\tID:1a\tSM:1a\tLB:1a\tPL:illumina\tPU:barcode" \
>1A.hiseq20110714_lane4_read12_w4q10m35_N.sam

