#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/mapping/2A

#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan/2A/hiseq_20110824_lane4_w4q20m35_N.1.fq \
#>2A.hiseq_20110824_lane4_w4q20m35_N.1.sai
#
#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan/2A/hiseq_20110824_lane4_w4q20m35_N.2.fq \
#>2A.hiseq_20110824_lane4_w4q20m35_N.2.sai


bwa sampe  \
/netshare1/home1/people/hansun/GATK/bwa/hg19 \
2A.hiseq_20110824_lane4_w4q20m35_N.1.sai \
2A.hiseq_20110824_lane4_w4q20m35_N.2.sai \
/netshare1/home1/szzhongxin/proj1/fudan/2A/hiseq_20110824_lane4_w4q20m35_N.1.fq \
/netshare1/home1/szzhongxin/proj1/fudan/2A/hiseq_20110824_lane4_w4q20m35_N.2.fq \
-r "@RG\tID:2a\tSM:2a\tLB:2a\tPL:illumina\tPU:barcode" \
>2A.hiseq_20110824_lane4_w4q20m35_N.sam

