#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/mapping/4A

#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan/4A/hiseq_20110824_lane7_w4q20m35_N.1.fq \
#>4A.hiseq_20110824_lane7_w4q20m35_N.1.sai
#
#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan/4A/hiseq_20110824_lane7_w4q20m35_N.2.fq \
#>4A.hiseq_20110824_lane7_w4q20m35_N.2.sai


bwa sampe \
-r "@RG\tID:4a\tSM:4a\tLB:4a\tPL:illumina\tPU:barcode" \
/netshare1/home1/people/hansun/GATK/bwa/hg19 \
4A.hiseq_20110824_lane7_w4q20m35_N.1.sai \
4A.hiseq_20110824_lane7_w4q20m35_N.2.sai \
/netshare1/home1/szzhongxin/proj1/fudan/4A/hiseq_20110824_lane7_w4q20m35_N.1.fq \
/netshare1/home1/szzhongxin/proj1/fudan/4A/hiseq_20110824_lane7_w4q20m35_N.2.fq \
>4A.hiseq_20110824_lane7_w4q20m35_N.sam

