#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/mapping/5A

#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan/5A/hiseq20110714_lane5_read12_w4q10m35_N.1.fq \
#>5A.hiseq20110714_lane5_read12_w4q10m35_N.1.sai
#
#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan/5A/hiseq20110714_lane5_read12_w4q10m35_N.2.fq \
#>5A.hiseq20110714_lane5_read12_w4q10m35_N.2.sai


bwa sampe  \
/netshare1/home1/people/hansun/GATK/bwa/hg19 \
5A.hiseq20110714_lane5_read12_w4q10m35_N.1.sai \
5A.hiseq20110714_lane5_read12_w4q10m35_N.2.sai \
/netshare1/home1/szzhongxin/proj1/fudan/5A/hiseq20110714_lane5_read12_w4q10m35_N.1.fq \
/netshare1/home1/szzhongxin/proj1/fudan/5A/hiseq20110714_lane5_read12_w4q10m35_N.2.fq \
-r "@RG\tID:5a\tSM:5a\tLB:5a\tPL:illumina\tPU:barcode" \
>5A.hiseq20110714_lane5_read12_w4q10m35_N.sam

