#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/mapping/6A

#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan/6A/hiseq_20110908_lane2_w4q20m35_N.1.fq \
#>6A.hiseq_20110908_lane2_w4q20m35_N.1.sai
#
#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan/6A/hiseq_20110908_lane2_w4q20m35_N.2.fq \
#>6A.hiseq_20110908_lane2_w4q20m35_N.2.sai


bwa sampe  \
/netshare1/home1/people/hansun/GATK/bwa/hg19 \
6A.hiseq_20110908_lane2_w4q20m35_N.1.sai \
6A.hiseq_20110908_lane2_w4q20m35_N.2.sai \
/netshare1/home1/szzhongxin/proj1/fudan/6A/hiseq_20110908_lane2_w4q20m35_N.1.fq \
/netshare1/home1/szzhongxin/proj1/fudan/6A/hiseq_20110908_lane2_w4q20m35_N.2.fq \
-r "@RG\tID:6a\tSM:6a\tLB:6a\tPL:illumina\tPU:barcode" \
>6A.hiseq_20110908_lane2_w4q20m35_N.sam

