#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/mapping/7A

#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan/7A/hiseq_20110908_lane3_w4q20m35_N.1.fq \
#>7A.hiseq_20110908_lane3_w4q20m35_N.1.sai
#
#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan/7A/hiseq_20110908_lane3_w4q20m35_N.2.fq \
#>7A.hiseq_20110908_lane3_w4q20m35_N.2.sai


bwa sampe  \
/netshare1/home1/people/hansun/GATK/bwa/hg19 \
7A.hiseq_20110908_lane3_w4q20m35_N.1.sai \
7A.hiseq_20110908_lane3_w4q20m35_N.2.sai \
/netshare1/home1/szzhongxin/proj1/fudan/7A/hiseq_20110908_lane3_w4q20m35_N.1.fq \
/netshare1/home1/szzhongxin/proj1/fudan/7A/hiseq_20110908_lane3_w4q20m35_N.2.fq \
-r "@RG\tID:7a\tSM:7a\tLB:7a\tPL:illumina\tPU:barcode" \
>7A.hiseq_20110908_lane3_w4q20m35_N.sam

