#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/mapping/9A

#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan/9A/9A_0107_w2q20m35_N_1.fq \
#>9A.9A_0107_w2q20m35_N_1.sai

#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan/9A/9A_0107_w2q20m35_N_2.fq \
#>9A.9A_0107_w2q20m35_N_2.sai


bwa sampe  \
/netshare1/home1/people/hansun/GATK/bwa/hg19 \
9A.9A_0107_w2q20m35_N_1.sai \
9A.9A_0107_w2q20m35_N_2.sai \
/netshare1/home1/szzhongxin/proj1/fudan/9A/9A_0107_w2q20m35_N_1.fq \
/netshare1/home1/szzhongxin/proj1/fudan/9A/9A_0107_w2q20m35_N_2.fq \
-r "@RG\tID:9a\tSM:9a\tLB:9a\tPL:illumina\tPU:barcode" \
>9A.9A_0107_w2q20m35_N.sam
