#!/bin/bash

read1fq=M7B_ATGTCA_L007_w4q20m35_N_1.fq
read2fq=M7B_ATGTCA_L007_w4q20m35_N_2.fq
read1sai=M7B_ATGTCA_L007_w4q20m35_N_1.sai
read2sai=M7B_ATGTCA_L007_w4q20m35_N_2.sai
readsam=7B.ATGTCA_L007_w4q20m35_N.sam
bam=7B.ATGTCA_L007_w4q20m35_N.bam
bamsorted=7B.ATGTCA_L007_w4q20m35_N.sorted

bamsortedbam=7B.ATGTCA_L007_w4q20m35_N.sorted.bam
BAM=7B.bam



cd  /netshare1/home1/szzhongxin/proj1/hansun/Viruses/mapping4/7B

#bwa aln -I -t 6 \
#/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
#/netshare1/home1/szzhongxin/proj1/fudan4/7B/$read1fq \
#>$read1sai
#
#bwa aln -I -t 6 \
#/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
#/netshare1/home1/szzhongxin/proj1/fudan4/7B/$read2fq \
#>$read2sai
#
#
#bwa sampe  \
#/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
#$read1sai \
#$read2sai \
#/netshare1/home1/szzhongxin/proj1/fudan4/7B/$read1fq \
#/netshare1/home1/szzhongxin/proj1/fudan4/7B/$read2fq \
#-r "@RG\tID:m7b\tSM:m7b\tLB:m7b\tPL:illumina\tPU:barcode" | \
#samtools view -bS -o $bam -
#
#samtools  sort $bam $bamsorted


mv $bamsortedbam $BAM
samtools index $BAM
