#!/bin/bash

read1fq=M7B_ATGTCA_L007_w4q20m35_N_1.fq
read2fq=M7B_ATGTCA_L007_w4q20m35_N_2.fq
read1sai=M7B_ATGTCA_L007_w4q20m35_N_1.sai
read2sai=M7B_ATGTCA_L007_w4q20m35_N_2.sai
readsam=7B.ATGTCA_L007_w4q20m35_N.sam


cd  /netshare1/home1/szzhongxin/proj1/hansun/mapping4/7B

bwa aln -I -t 8 \
/netshare1/home1/people/hansun/GATK/bwa/hg19 \
/netshare1/home1/szzhongxin/proj1/fudan4/7B/$read1fq \
>$read1sai

bwa aln -I -t 8 \
/netshare1/home1/people/hansun/GATK/bwa/hg19 \
/netshare1/home1/szzhongxin/proj1/fudan4/7B/$read2fq \
>$read2sai


bwa sampe  \
/netshare1/home1/people/hansun/GATK/bwa/hg19 \
$read1sai \
$read2sai \
/netshare1/home1/szzhongxin/proj1/fudan4/7B/$read1fq \
/netshare1/home1/szzhongxin/proj1/fudan4/7B/$read2fq \
-r "@RG\tID:m7b\tSM:m7b\tLB:m7b\tPL:illumina\tPU:barcode" \
>$readsam

