#!/bin/bash

cd /netshare1/home1/szzhongxin/proj1/hansun/aftmapping2

java -Xmx4g -jar \
/netshare1/home1/people/hansun/GATK/GenomeAnalysisTK.jar \
-I /netshare1/home1/szzhongxin/proj1/hansun/mapping2/6A/6A.bam \
-R /netshare1/home1/people/hansun/GATK/bundle/ucsc.hg19.fasta \
-T IndelRealigner \
-targetIntervals hg19.intervals \
-o 6A/6A.realigned.bam \
--known /netshare1/home1/people/hansun/GATK/bundle/1000G_biallelic.indels.hg19.vcf \
--known /netshare1/home1/people/hansun/GATK/bundle/Mills_Devine_2hit.indels.hg19.vcf
