#!/bin/bash

cd /netshare1/home1/szzhongxin/proj1/hansun/aftmapping3

java -Xmx20g -jar \
/netshare1/home1/people/hansun/GATK/GenomeAnalysisTK.jar -T RealignerTargetCreator \
-R /netshare1/home1/people/hansun/GATK/bundle/ucsc.hg19.fasta \
-o hg19.intervals \
--known /netshare1/home1/people/hansun/GATK/bundle/1000G_biallelic.indels.hg19.vcf \
--known /netshare1/home1/people/hansun/GATK/bundle/Mills_Devine_2hit.indels.hg19.vcf
