#!/bin/bash

cd /netshare1/home1/szzhongxin/proj1/hansun/aftmapping3

java -Xmx6g -jar \
/netshare1/home1/people/hansun/GATK/GenomeAnalysisTK.jar -T RealignerTargetCreator \
-I /netshare1/home1/szzhongxin/proj1/hansun/mapping3/10B/10B.bam \
-I /netshare1/home1/szzhongxin/proj1/hansun/mapping3/4B/4B.bam \
-I /netshare1/home1/szzhongxin/proj1/hansun/mapping3/5B/5B.bam \
-I /netshare1/home1/szzhongxin/proj1/hansun/mapping3/9B/9B.bam \
-I /netshare1/home1/szzhongxin/proj1/hansun/mapping4/10B/10B.bam \
-I /netshare1/home1/szzhongxin/proj1/hansun/mapping4/5B/5B.bam \
-I /netshare1/home1/szzhongxin/proj1/hansun/mapping4/6B/6B.bam \
-I /netshare1/home1/szzhongxin/proj1/hansun/mapping4/7B/7B.bam \
-R /netshare1/home1/people/hansun/GATK/bundle/ucsc.hg19.fasta \
-o hg19.intervals.full \
--known /netshare1/home1/people/hansun/GATK/bundle/1000G_biallelic.indels.hg19.vcf \
--known /netshare1/home1/people/hansun/GATK/bundle/Mills_Devine_2hit.indels.hg19.vcf
