#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/Viruses/mapping2/7A

#bwa aln -I -t 6 \
#/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
#/netshare1/home1/szzhongxin/proj1/fudan2/7A/hiseq_20111018_lane6_w4q20m35_N.1.fq \
#>7A.hiseq_20111018_lane6_w4q20m35_N.1.sai
#
#bwa aln -I -t 6 \
#/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
#/netshare1/home1/szzhongxin/proj1/fudan2/7A/hiseq_20111018_lane6_w4q20m35_N.2.fq \
#>7A.hiseq_20111018_lane6_w4q20m35_N.2.sai
#
#
#bwa sampe  \
#/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
#7A.hiseq_20111018_lane6_w4q20m35_N.1.sai \
#7A.hiseq_20111018_lane6_w4q20m35_N.2.sai \
#/netshare1/home1/szzhongxin/proj1/fudan2/7A/hiseq_20111018_lane6_w4q20m35_N.1.fq \
#/netshare1/home1/szzhongxin/proj1/fudan2/7A/hiseq_20111018_lane6_w4q20m35_N.2.fq \
#-r "@RG\tID:m7a\tSM:m7a\tLB:m7a\tPL:illumina\tPU:barcode" | \
#samtools view -bS -o 7A.hiseq_20111018_lane6_w4q20m35_N.bam -
#
#samtools  sort  7A.hiseq_20111018_lane6_w4q20m35_N.bam  7A.hiseq_20111018_lane6_w4q20m35_N.sorted

mv 7A.hiseq_20111018_lane6_w4q20m35_N.sorted.bam 7A.bam
samtools index 7A.bam

