#!/bin/bash

cd /netshare1/home1/szzhongxin/proj1/hansun/mapping2/4A
samtools view -bS -o 4A.hiseq_20110926_lane8_w4q20m35_N.bam 4A.hiseq_20110926_lane8_w4q20m35_N.sam
rm 4A.hiseq_20110926_lane8_w4q20m35_N.sam
samtools  sort 4A.hiseq_20110926_lane8_w4q20m35_N.bam 4A.hiseq_20110926_lane8_w4q20m35_N.sorted
samtools  flagstat 4A.hiseq_20110926_lane8_w4q20m35_N.sorted.bam >4A.stat
mv 4A.hiseq_20110926_lane8_w4q20m35_N.sorted.bam 4A.bam


samtools index 4A.bam
