cd /netshare1/home1/szzhongxin/proj1/hansun/annotation/exon_type/PASS_EXONIC_FRAMESHIFT

python sampleDistribution.py snpindel_indel3030_raw.indel.recalibrated.annovar.exonic_variant_function_new_frameshift_deletion
python sampleDistribution.py snpindel_indel3030_raw.indel.recalibrated.annovar.exonic_variant_function_new_frameshift_insertion
python sampleDistribution.py snpindel2_indel3030_raw.indel.recalibrated.annovar.exonic_variant_function_new_frameshift_deletion
python sampleDistribution.py snpindel2_indel3030_raw.indel.recalibrated.annovar.exonic_variant_function_new_frameshift_insertion

