#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/mapping2/7A

#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan2/7A/hiseq_20111018_lane6_w4q20m35_N.1.fq \
#>7A.hiseq_20111018_lane6_w4q20m35_N.1.sai
#
#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan2/7A/hiseq_20111018_lane6_w4q20m35_N.2.fq \
#>7A.hiseq_20111018_lane6_w4q20m35_N.2.sai


bwa sampe  \
/netshare1/home1/people/hansun/GATK/bwa/hg19 \
7A.hiseq_20111018_lane6_w4q20m35_N.1.sai \
7A.hiseq_20111018_lane6_w4q20m35_N.2.sai \
/netshare1/home1/szzhongxin/proj1/fudan2/7A/hiseq_20111018_lane6_w4q20m35_N.1.fq \
/netshare1/home1/szzhongxin/proj1/fudan2/7A/hiseq_20111018_lane6_w4q20m35_N.2.fq \
-r "@RG\tID:m7a\tSM:m7a\tLB:m7a\tPL:illumina\tPU:barcode" \
>7A.hiseq_20111018_lane6_w4q20m35_N.sam

