#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/mapping2/8A

#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan2/8A/hiseq_20111018_lane7_w4q20m35_N.1.fq \
#>8A.hiseq_20111018_lane7_w4q20m35_N.1.sai
#
#bwa aln -I -t 6 \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan2/8A/hiseq_20111018_lane7_w4q20m35_N.2.fq \
#>8A.hiseq_20111018_lane7_w4q20m35_N.2.sai


bwa sampe  \
/netshare1/home1/people/hansun/GATK/bwa/hg19 \
8A.hiseq_20111018_lane7_w4q20m35_N.1.sai \
8A.hiseq_20111018_lane7_w4q20m35_N.2.sai \
/netshare1/home1/szzhongxin/proj1/fudan2/8A/hiseq_20111018_lane7_w4q20m35_N.1.fq \
/netshare1/home1/szzhongxin/proj1/fudan2/8A/hiseq_20111018_lane7_w4q20m35_N.2.fq \
-r "@RG\tID:m8a\tSM:m8a\tLB:m8a\tPL:illumina\tPU:barcode" \
>8A.hiseq_20111018_lane7_w4q20m35_N.sam

