#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/mapping2/9A

#bwa aln -I  \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan2/9A/D-M9A_w4q20m35_N_1.fq \
#>9A.D-M9A_w4q20m35_N_1.sai

#bwa aln -I  \
#/netshare1/home1/people/hansun/GATK/bwa/hg19 \
#/netshare1/home1/szzhongxin/proj1/fudan2/9A/D-M9A_w4q20m35_N_2.fq \
#>9A.D-M9A_w4q20m35_N_2.sai


bwa sampe  \
/netshare1/home1/people/hansun/GATK/bwa/hg19 \
9A.D-M9A_w4q20m35_N_1.sai \
9A.D-M9A_w4q20m35_N_2.sai \
/netshare1/home1/szzhongxin/proj1/fudan2/9A/D-M9A_w4q20m35_N_1.fq \
/netshare1/home1/szzhongxin/proj1/fudan2/9A/D-M9A_w4q20m35_N_2.fq \
-r "@RG\tID:m9a\tSM:m9a\tLB:m9a\tPL:illumina\tPU:barcode" \
>9A.D-M9A_w4q20m35_N.sam

