#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/Viruses/mapping2/6A

#bwa aln -I -t 6 \
#/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
#/netshare1/home1/szzhongxin/proj1/fudan2/6A/hiseq_20111018_lane5_w4q20m35_N.1.fq \
#>6A.hiseq_20111018_lane5_w4q20m35_N.1.sai
##
#bwa aln -I -t 6 \
#/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
#/netshare1/home1/szzhongxin/proj1/fudan2/6A/hiseq_20111018_lane5_w4q20m35_N.2.fq \
#>6A.hiseq_20111018_lane5_w4q20m35_N.2.sai
#
#
#bwa sampe  \
#/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruses \
#6A.hiseq_20111018_lane5_w4q20m35_N.1.sai \
#6A.hiseq_20111018_lane5_w4q20m35_N.2.sai \
#/netshare1/home1/szzhongxin/proj1/fudan2/6A/hiseq_20111018_lane5_w4q20m35_N.1.fq \
#/netshare1/home1/szzhongxin/proj1/fudan2/6A/hiseq_20111018_lane5_w4q20m35_N.2.fq \
#-r "@RG\tID:m6a\tSM:m6a\tLB:m6a\tPL:illumina\tPU:barcode" | \
#samtools view -bS -o 6A.hiseq_20111018_lane5_w4q20m35_N.bam -
#
#samtools  sort 6A.hiseq_20111018_lane5_w4q20m35_N.bam 6A.hiseq_20111018_lane5_w4q20m35_N.sorted

mv 6A.hiseq_20111018_lane5_w4q20m35_N.sorted.bam 6A.bam
samtools index 6A.bam

